### ISSUE TITLE
REST API call for retrieving annotations added by the Editor Tool

### ISSUE THREAD

**Issue by jthomsen** [linkedtv/platform#14]
sthing like /annotation?source=editortool&origin=enrichment/basic

**Comment by alisarioglu** [comment]
To get the annotations generated by the editor tool, the following parameter can be added to the url.  '?wasAttributedTo=http%3A%2F%2Fdata.linkedtv.eu%2Forganization%2FSV%2FEditorTool’.

Here is an example where annatotions will be returned that related to the media resource '8a8187f2-3fc8-cb54-0140-7dccd76f0001' for the first 5 minutes and generated with the editor tool:

http://data.linkedtv.eu/annotation?hasTarget.isFragmentOf=http%3A%2F%2Fdata.linkedtv.eu%2Fmedia%2F8a8187f2-3fc8-cb54-0140-7dccd76f0001&max-hasTarget.temporalEnd=300&motivatedBy=linking&wasAttributedTo=http%3A%2F%2Fdata.linkedtv.eu%2Forganization%2FSV%2FEditorTool&_view=full
