### ISSUE TITLE
proxy server received an invalid response from an upstream server.

### ISSUE THREAD

**Issue by jthomsen** [linkedtv/platform#15]
OK firstmost I am not getting access via the REST API right now. 
/\* Lyndon Nixon 08/10/2013 */ 

http://data.linkedtv.eu/mediaresource/8a8187f2-3fc8-cb54-0140-7dd099380002/mediafragment returns

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /mediaresource/8a8187f2-3fc8-cb54-0140-7dd099380002/mediafragment.
Reason: Error reading from remote server

**Comment by jthomsen** [comment]
/\* Ali Sarioglu 08/10/2013 */

this is a known bug that base on the ordering (off the mediafragments). Sometimes it takes to much time to get a result and the apache webserver return this proxy error.

I will let you know when I fixed it.

**Comment by alisarioglu** [comment]
Fixed.
