### ISSUE TITLE
display the thumbnail of a media resource

### ISSUE THREAD

**Issue by jthomsen** [linkedtv/platform#25]
why is it forbidden to see the thumbnail of a media resource, e.g.
http://images1.noterik.com/domain/linkedtv/user/rbb/video/1621/shots/1/?

raised by @rtroncy

**Comment by pietervanleeuwen** [comment]
Because you didn't specifiy what thumbnail you wanted to see ;-) For this particular video we have 1730 thumbnails available. Ranging from http://images1.noterik.com/domain/linkedtv/user/rbb/video/1621/shots/1/h/0/m/0/sec1.jpg to http://images1.noterik.com/domain/linkedtv/user/rbb/video/1621/shots/1/h/0/m/28/sec51.jpg

The thumbnail locator is a base uri as we store an image of every second of video available, convenient for using in frontend applications where you don't want to load the entire video but give a quick visual representation of a certain moment in the video.
For more information about the syntax check http://www.linkedtv.eu/wiki/index.php/Thumbnail_Locator

**Comment by rtroncy** [comment]
Ah! I was not aware that what is displayed in the dashboard (http://api.linkedtv.eu/mediaresource/154307a8-0058-4946-839d-cd802fe0aad5) as thumbnail-locator was actually a base URI ! @jthomsen was this ever documented?

Thanks for the clarification @pietervanleeuwen. In this case, what I was more looking for is the video poster, i.e. the single image/frame that represents the video before video data is loaded. It could be set to be the first frame, so in your case, http://images1.noterik.com/domain/linkedtv/user/rbb/video/1621/shots/1/h/0/m/0/sec10.jpg right?

**Comment by pietervanleeuwen** [comment]
@rtroncy I understand some of the confusement about this as for the ET it was discussed that it would be a nice feature if the editor could set a screenshot that represents the video.

Setting the image to the first frame does often give issues with black screens we know from experience (and see http://images1.noterik.com/domain/linkedtv/user/avro/video/100/shots/1/h/0/m/0/sec1.jpg for an example TKK show). So it's better to take the frame after 10 seconds as a default (http://images1.noterik.com/domain/linkedtv/user/avro/video/100/shots/1/h/0/m/0/sec10.jpg)

**Comment by rtroncy** [comment]
Ah, ok! Whatever is the best then :-)
I think you should still generate keyframes every x second for fast previewing a video but I think you should  also add a specific frame as an illustration of the entire video, and call it a "poster" as YouTube does.

@jthomsen Can the platform handles a new field "poster" when ingesting new videos?

**Comment by jthomsen** [comment]
yes, this should be no problem; a "poster" would be just another MediaResourceRelation with:
RelationTarget: {KeyframeURI}
RelationType: "Poster"
you can add as many MediaResourceRelations with arbitrary RelationTypes (they are just strings) as you like

**Comment by jblom** [comment]
Hi Jan, Raphael, Pieter, Lyndon,

shamefully open question (I appreciate Raphael's problem of being swamped
with mail and trying to do some actual work):

Does the RDF/model now support storing a poster for videos? Also is there a
way to store posters for chapters?

If so, could anyone show me how to do this?

(Really into ET development now and trying to keep up with all the
important discussions)

Best,

Jaap

2014-07-22 22:40 GMT+02:00 Jan Thomsen notifications@github.com:

> yes, this should be no problem; a "poster" would be just another
> MediaResourceRelation with:
> RelationTarget:
> RelationType: "Poster"
> you can add as many MediaResourceRelations with arbitrary RelationTypes
> (they are just strings) as you like
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linkedtv/platform/issues/25#issuecomment-49797616.

## 

_Jaap Blom_

Projectmedewerker R&D

_T_ 035 - 677 1930
_Aanwezig:_ ma,di,wo,do,vr
 http://www.beeldengeluid.nl _Nederlands Instituut voor Beeld en Geluid_
*
Media Parkboulevard 1, 1217 WE  Hilversum | Postbus 1060, 1200 BB  Hilversum | *
_beeldengeluid.nl_ http://www.beeldengeluid.nl

**Comment by rtroncy** [comment]
The RDF/data model we use in LinkedTV makes use of the Ontology for Media Resource so it has always been able to attach a poster to a media resource, via the ma:hasRelatedResource property or one of its sub-property depending on the relation.type, see also the [spec](http://www.w3.org/TR/mediaont-10/#correspondence-between-the-informal-ontology-and-the-rdf-representation)

You should generate a triple like:
 `<http://data.linkedtv.eu/mediaresource/154307a8-0058-4946-839d-cd802fe0aad5> ma:hasRelatedImage :Poster`
where :Poster is actually the link to the jpg/png resource, e.g. `<http://images1.noterik.com/domain/linkedtv/user/avro/video/100/shots/1/h/0/m/0/sec10.jpg>`

**Comment by jblom** [comment]
thanks Raphael for the clear/quick answer! This is really helpful. Will
implement this in this way.

Best,

Jaap

2014-07-23 9:00 GMT+02:00 Raphael Troncy notifications@github.com:

> The RDF/data model we use in LinkedTV makes use of the Ontology for Media
> Resource so it has always been able to attach a poster to a media resource,
> via the ma:hasRelatedResource property or one of its sub-property depending
> on the relation.type, see also the (spec)[
> http://www.w3.org/TR/mediaont-10/#correspondence-between-the-informal-ontology-and-the-rdf-representation
> ]
> 
> You should generate a triple like:
> http://data.linkedtv.eu/mediaresource/154307a8-0058-4946-839d-cd802fe0aad5
> ma:hasRelatedImage :Poster
> where :Poster is actually the link to the jpg/png resource, e.g.
> http://images1.noterik.com/domain/linkedtv/user/avro/video/100/shots/1/h/0/m/0/sec10.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linkedtv/platform/issues/25#issuecomment-49839549.

## 

_Jaap Blom_

Projectmedewerker R&D

_T_ 035 - 677 1930
_Aanwezig:_ ma,di,wo,do,vr
 http://www.beeldengeluid.nl _Nederlands Instituut voor Beeld en Geluid_
*
Media Parkboulevard 1, 1217 WE  Hilversum | Postbus 1060, 1200 BB  Hilversum | *
_beeldengeluid.nl_ http://www.beeldengeluid.nl

**Comment by jthomsen** [comment]
closed as issue doesn't seem to be open any longer

**Comment by rtroncy** [comment]
What is displayed in the platform is still misleading. Hence, the [platform](http://api.linkedtv.eu/mediaresource/154307a8-0058-4946-839d-cd802fe0aad5) still displays a thumbnail locator while the value actually corresponds to a base URI from which one can get a poster, e.g. by adding 'h/0/m/0/sec10.jpg ' to the URL. Either you should rename this into base URI, or you should provide a real thumbnail locator IMHO
