### ISSUE TITLE
List of known prefixes has been deleted

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/platform#40]
The list of known prefixes in the SPARQL endpoint has been reset, see http://data.linkedtv.eu/sparql?nsdecl which is unfortunate and makes all queries more complicated since we need to always add a lot of prefixed! At the minimum, `linkedtv`, `prov`, `ma`, `nsa`, etc. should be defined

**Comment by alisarioglu** [comment]
Following namespaces are added in the new(current) virtuoso

```
PREFIX linkedtv: <http://data.linkedtv.eu/ontologies/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ma: <http://www.w3.org/ns/ma-ont#>
PREFIX nsa: <http://multimedialab.elis.ugent.be/organon/ontologies/ninsuna#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX po: <http://purl.org/ontology/po/>
```

Here the list of namespaces in the old virtuoso http://data.linkedtv.eu:8892/sparql?nsdecl.
If more is desired, please reopen this issue.
