### ISSUE TITLE
Flush Solr Index

### ISSUE THREAD

**Issue by jluisred** [linkedtv/platform#42]
Remove the whole set of documents from the Solr index before reindexing with upcoming TV2Lucene versions. Tentative approach:

http://stackoverflow.com/questions/7722508/how-to-delete-all-data-from-solr-and-hbase

**Comment by jblom** [comment]
I'm not sure why the SOLR index must be deleted, but in any case this might be a good opportunity to add a separate field to see whether a document (chapter) is curated or not.

Using this field the TV2Lucene should only update/delete non-curated chapters.

**Comment by rtroncy** [comment]
> I'm not sure why the SOLR index must be deleted

The Solr index contains a lot of crap, old documents, etc. not taking 
into account the numerous updates done so far.

> Using this field the TV2Lucene should only update/delete non-curated
> chapters.

TV2Lucene does not update/delete at all.

**Comment by jluisred** [comment]
After some internal discussion between the partners involved, we have agreed on:

1) Adding a new boolean parameter to the Solr index called "curated", initially set to "false" by TV2Lucene. New version coming in the next minutes.
2) Flush the Solr index and start from scratch. The ET can sync the changes again when restarted, @jblom correct me if I'm wrong. Ideally, this full flushing won't be needed again.
3) From now on, the curated chapters are easily differentiable in the index, so it would be possible to do selective removal in case it's necessary.

**Comment by jblom** [comment]
after you have updated the index (after deleting everything), I will adjust my code to make sure that the ET creates SOLR docs with the curated parameter set to `true`. Also the ET has a synchronization option (after I update): when the page is loaded the ET synchs all curated chapters with the SOLR index documents.

**Comment by jluisred** [comment]
Ok, thanks @jblom .
New TV2Lucene version including "curated" field has just been published.

**Comment by jluisred** [comment]
Flushing planned for tomorrow by @jthomsen

**Comment by jthomsen** [comment]
All three indexes have been flushed
